### PR TITLE
Tried to fix forgot password

### PR DESCRIPTION
**Pull request by Buzzec**
Signed-off-by: buzzec <buzzec@buzzec.net>

### CODE REVIEW

**Comment by cdconn00** [comment]
I know you're still working on this, but, make sure bootstrap columns have specified lengths and arent left as "col". This could cause usability issues and prevent the display in mobile viewports from being correct.

**Review by cdconn00 — CHANGES_REQUESTED** [review]
I know you're still working on this, but, make sure bootstrap columns have specified lengths and arent left as "col". This could cause usability issues and prevent the display in mobile viewports from being correct.

See app/views/devise/shared/_sign_in_reg.html.erb

**Comment by Buzzec** [comment]
IT WORKS! Just need to set an env variable on production when we deploy to master

**Comment by Buzzec** [comment]
This also updates to Ruby 3.0.1

**Review by cdconn00 — APPROVED** [review]
LGTM just need to fix that merge conflict.

**Pull request merged**
